# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ac93520b9cf36a1fca883e8e8b061ac947e4f9d996a4187a54995fc3c2be6d858bc9e5f97471ea8e6ca6bebf6bb4f4b27b780d964e175914e03fb4a3febe75

test:
  secret_key_base: 50bb766b9220ac286a2ce78395628e00a01f50baa41e57718af63e7e3bde0812c9274cf9a042b0f2fd3a0adeac9de015f306215bc185f0404fab7e9f704a7269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
